language: node_js
node_js:
- '0.11'
before_install: 
install:
- npm install
script:
- npm run build
- npm run test
- npm run cover
- npm run report
env:
  global:
  - secure: PG3I3wL+CkhHgAtxBjrp3X0l3VL2LMWqC62OWAg8t7rrrrXsD9Px4tH8gPKKEiYwgz/Qj9MIj0jSIpWF9vgisI7PlFHLnz8ezRP0Pr8zpwZy1ExOAoJrF25cS1pggW1V/lfkyYAaxF0V/uEB2/eMfByl3zf2cDxoLW8TUtx5KYVXeTneksmJr7y5duaHNo/tjfQUxuGN2K5TXzYCMTTOfiXG875ZawcEoRRvMVvLEj+2X1+w9xkqLlTURUXmnoXfSmzTUm/zBCDl3gxUTGII1Hesra53T7obuEc3vmwkTNhJXou5qKQi8nq7HUQvrstD3PYIeXOZY4h0/qKIu0H/bpWlBBj+CFTnP3fdeR+S+MEt1/Vqn3iUYgOI5Rj1RMgR9XFcwafn3rb2K+87pzi2RR5vbT8yQniEjqS/kfvtXJcPFqGROwkuKDKZ0TiLFSBckgRc4+w5Y0N23/1SOAkjQab6smEmkBk4P9OP8zUwLDLy1qy8Mux+8ZeViDNo4hEtZqhA2bbZj+GhuJgLQ9xb46AKcBJhSIkFmkk9WcZheGr3G+/uBNIGvF/5x/E+2AmSPGgWWxvNx8tVNulWT7cGZQnpp/KzGo2etV0lWC7iIrB8J47EDpkGjg/upEMSL9CKfb8F15TEQ5YvAnjGGgKaaIVBgWpRRWm9qJa6SdN4Vzc=
  - secure: XRehF0VJwz1oUb+uAqypu6uHDUIkOwkFw8ElOgYEnhCmp1ZSoh69dIK6LC8yS99PMwtGpTMUctW0htmJqP0Grf06iR5Rc+7nXDjqAOQWuzbdx75Skq96CbuFDqA8Gp4/taFjty2TTyzM4hdNNAlVOPXtxi6icbkPCNX/0vMV32oyZCL49hOD45Jyv7OJ1zzc2y+H3IS0+/VeKGL4YByFKzZqXwiZXjudPO/z+QxrSA6jg971smWTA4qBCjhCPnrga9F4xrxqnbkHTN3ann1q5PuW+oCYELTCi0u6IGKYpazqj7uh+efMV+9/0/3sqZZVigA7lcAiqpxnJzRttgSDEOz4ze6ZfbkJKu0FrCp1XtdP7Ys/eA6mcZAlE4fa0umap6AQmZA958To3IAvuX0if5v9v2gI0dyIUJ5a+4nJc3w9x2phS3KRgzAXiI416L6hSa1C0xbkq4l5OdYZvumoJ1nUARZm4aeqlZPbwGacP8xAIJGo2nbY4K/insRyOf2CR2dnL+noym/T1NRXAKU7ZYxPtB04kx6P9R7MwpcXUhnALWL7iG6TrJrKJII7gitM0U2TcTGRAU82BqYqEjOBU8LHODlwwNUMtmsp2HX0/lz2wVJlasiUHQMMpgzzOjASEeybklo/audFuI3sqWEpk+hvwSspcuwOPBs0HNkT4Gc=
